# Generated by Django 3.2.5 on 2023-01-30 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management_App', '0002_remove_attendancereport_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='attendence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Backend_Management_App.attendance'),
            preserve_default=False,
        ),
    ]
