# Generated by Django 3.2.5 on 2023-01-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management_App', '0007_feedbackstaff_feedbackstudent_notificationstaff_notificationstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstaff',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedbackstaff',
            name='feedback_reply',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='feedback_reply',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notificationstaff',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
