# Generated by Django 3.2.5 on 2023-03-28 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management_App', '0010_remove_notice_notice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
